import { countSentenceBlanks } from './questionQuality.js'

const SOURCE = '英語演習I 2中・平常授業'

const REWRITE_QUESTION_IDS = new Set([
  'reg27-07', 'reg27-08', 'reg27-09', 'reg27-10', 'reg27-11',
  'reg15-07', 'reg15-08', 'reg15-09', 'reg15-10',
  'regplus-06', 'regplus-07', 'regplus-08',
  'regopt4-01', 'regopt4-02', 'regopt4-03', 'regopt4-04', 'regopt4-05',
])

const make = (id, lesson, topic, difficulty, type, data) => ({
  id, lesson, topic, difficulty, type,
  rewrite: REWRITE_QUESTION_IDS.has(id),
  prompt: type === 'reorder' ? '日本語の意味に合うように、語句を並べかえなさい。' : type === 'choice' ? '空所に入る最も適切なものを選びなさい。' : '空所に入る語句を入力しなさい。',
  source: `${SOURCE}・${lesson}`,
  blankCount: countSentenceBlanks(data.sentence || ''),
  ...data,
})

const choice = (id, lesson, topic, difficulty, sentence, choices, answer, explanation, japanese = '') => make(id, lesson, topic, difficulty, 'choice', { sentence, choices, answer, answerLabel: answer, explanation, japanese, translation: japanese })
const fill = (id, lesson, topic, difficulty, sentence, answer, explanation, japanese = '', accepted = [answer]) => make(id, lesson, topic, difficulty, 'input', {
  sentence,
  answer,
  accepted,
  answerLabel: answer,
  explanation,
  translation: japanese,
  ...(countSentenceBlanks(sentence) === 0 ? { prompt: '日本語に合う英文を入力しなさい。' } : {}),
  ...(REWRITE_QUESTION_IDS.has(id) ? { prompt: '次の2文が同じ意味になるように、空所に入る語句を入力しなさい。' } : {}),
})
const reorder = (id, lesson, topic, difficulty, japanese, words, answer, explanation) => make(id, lesson, topic, difficulty, 'reorder', { japanese, words, answer, answerLabel: answer, explanation, translation: japanese })
const translateChoice = (id, lesson, topic, difficulty, sentence, answer, explanation, choices) => make(id, lesson, topic, difficulty, 'choice', { prompt: '下線部に注意して、正しい日本語訳を選びなさい。', sentence, choices, answer, answerLabel: answer, explanation })

export const REGULAR_QUESTIONS = [
  // Lesson 27: 助動詞
  fill('reg27-01', 'Lesson 27', '助動詞', 'starter', 'The answer (　　　) (　　　) right.', 'will be', '未来の推量や意志には will be を使います。', 'その答えは正しいでしょう。'),
  fill('reg27-02', 'Lesson 27', '助動詞', 'starter', 'It is raining heavily. You (　　　) drive carefully.', 'should', 'should は「〜すべきだ」という助言を表します。', '雨が激しく降っています。あなたは注意して運転すべきです。'),
  fill('reg27-03', 'Lesson 27', '助動詞', 'standard', 'I asked her some questions, but she (　　　) answer them.', "wouldn't", 'would not は「どうしても〜しようとしなかった」という拒否を表します。', '私は彼女にいくつか質問をしたが、彼女はどうしても答えようとしなかった。'),
  fill('reg27-04', 'Lesson 27', '助動詞', 'starter', 'There (　　　) (　　　) be a famous castle around here.', 'used to', 'used to be は「以前は〜があった」という過去の習慣・状態を表します。', '昔、このあたりには有名な城がありました。'),
  fill('reg27-05', 'Lesson 27', '助動詞', 'standard', 'There were a lot of beautiful flowers in the park. I (　　　) (　　　) taken pictures.', 'should have', 'should have + 過去分詞で「〜しておくべきだった」という過去の後悔を表します。', 'その公園にはたくさんの美しい花があった。写真を撮っておくべきだったなあ。'),
  fill('reg27-06', 'Lesson 27', '助動詞', 'standard', 'He (　　　) (　　　) tired because he played soccer all day yesterday.', 'must be', 'must be は、現在の状態についての強い推量「〜に違いない」を表します。', '彼は昨日一日中サッカーをしていたので、疲れているに違いない。'),
  fill('reg27-07', 'Lesson 27', '助動詞', 'starter', 'Let\'s sing a song together. (　　　) (　　　) sing a song?', 'Shall we', 'Shall we ...? は「〜しましょうか」と提案する表現です。', '一緒に歌を歌いましょう。歌を歌いませんか。'),
  fill('reg27-08', 'Lesson 27', '助動詞', 'starter', 'You must not park your car here. (　　　) park your car here.', "Don't", 'must not は禁止を表し、命令文では Don\'t を使えます。', 'ここに車を止めてはいけません。ここに車を止めないでください。'),
  fill('reg27-09', 'Lesson 27', '助動詞', 'starter', 'You needn\'t finish it by tomorrow. You (　　　) (　　　) (　　　) finish it by tomorrow.', "don't have to", 'needn\'t は don\'t have to と同じ「〜する必要はない」です。', '明日までにそれを終える必要はありません。', ["don't have to", 'do not have to']),
  fill('reg27-10', 'Lesson 27', '助動詞', 'starter', 'Must I do my homework before dinner? (　　　) I (　　　) (　　　) do my homework before dinner?', 'Do ... have to', '義務を尋ねる must は、疑問文では do ... have to に言い換えられます。', '夕食前に宿題をしなければなりませんか。', ['Do have to', 'Do I have to']),
  fill('reg27-11', 'Lesson 27', '助動詞', 'standard', 'You ought not to break your promise. You (　　　) (　　　) your promise.', "shouldn't break", 'ought not to は should not と同じ「〜すべきでない」です。', 'あなたは約束を破るべきではありません。'),
  reorder('reg27-12', 'Lesson 27', '助動詞', 'standard', '私たちはまた会うことができるでしょう。', ['we', 'will', 'be', 'able', 'to', 'meet', 'again.'], 'We will be able to meet again.', 'will be able to は「〜できるでしょう」という未来の可能を表します。'),
  reorder('reg27-13', 'Lesson 27', '助動詞', 'advanced', '彼はオリンピックでメダルを取る可能性が十分にある。', ['He', 'may', 'well', 'win', 'a', 'medal', 'at', 'the', 'Olympics.'], 'He may well win a medal at the Olympics.', 'may well は「十分〜する可能性がある」という意味です。'),
  reorder('reg27-14', 'Lesson 27', '助動詞', 'advanced', '盗みをするくらいなら、死んだほうがましだ。', ['I', 'would', 'rather', 'die', 'than', 'steal.'], 'I would rather die than steal.', 'would rather A than B は「BするよりAするほうがまし」です。'),
  reorder('reg27-15', 'Lesson 27', '助動詞', 'advanced', '君にはその会議に出席することが必要だ。', ['It', 'is', 'necessary', 'that', 'you', 'should', 'attend', 'the', 'meeting.'], 'It is necessary that you should attend the meeting.', 'It is necessary that ... should ... の形で必要性を表せます。'),
  choice('reg27-16', 'Lesson 27', '助動詞', 'starter', 'My brother and I (　　　) often make trips together when we were young.', ['would', 'shall', 'could', 'will'], 'would', '過去の習慣には would を使えます。'),
  choice('reg27-17', 'Lesson 27', '助動詞', 'starter', '(　　　) I carry your baggage?', ['Shall', 'Will', 'Ought', 'Would'], 'Shall', 'Shall I ...? は申し出を表します。'),
  choice('reg27-18', 'Lesson 27', '助動詞', 'starter', '(　　　) you lend me your bicycle?', ['May', 'Must', 'Will', 'Might'], 'May', 'May I ...? は丁寧な許可の依頼です。'),
  choice('reg27-19', 'Lesson 27', '助動詞', 'standard', 'She (　　　) come to the party because she had a cold.', ['should have', 'must have', 'need not have', 'may have'], 'may have', 'may have + 過去分詞は「〜したかもしれない」を表します。'),
  choice('reg27-20', 'Lesson 27', '助動詞', 'standard', 'He isn\'t rich, so he (　　　) bought such an expensive car.', ['may have', 'should have', 'must have', 'cannot have'], 'cannot have', 'cannot have + 過去分詞は「〜したはずがない」です。'),
  choice('reg27-21', 'Lesson 27', '助動詞', 'starter', 'I (　　　) invite him to the party if he is interested in it.', ['would often', "don't have to", 'would like to', 'should have'], 'would like to', 'would like to は「〜したい」という希望を表します。'),
  choice('reg27-22', 'Lesson 27', '助動詞', 'standard', 'Look at that dark cloud! It [may / can\'t] rain soon.', ['may', "can't"], 'may', '暗い雲から雨が降る可能性を may で表します。'),
  choice('reg27-23', 'Lesson 27', '助動詞', 'standard', 'It is surprising that you [must feel / should feel] that way.', ['must feel', 'should feel'], 'should feel', 'It is surprising that ... should ... は「〜とは驚きだ」という感情を表します。'),
  choice('reg27-24', 'Lesson 27', '助動詞', 'standard', 'It is important that you [should / can] be polite to others.', ['should', 'can'], 'should', 'It is important that ... should ... は必要・重要性を表します。'),
  choice('reg27-25', 'Lesson 27', '助動詞', 'advanced', 'She knows the movie well. She [must watch / must have watched] it many times.', ['must watch', 'must have watched'], 'must have watched', '過去の経験への推量なので must have watched です。'),
  choice('reg27-26', 'Lesson 27', '助動詞', 'starter', 'He will arrive soon, so you [might as well / as might well] wait for him.', ['might as well', 'as might well'], 'might as well', 'might as well は「〜したほうがよい」を表します。'),
  choice('reg27-27', 'Lesson 27', '助動詞', 'starter', 'The bicycle is mine, so you [must / can] use it.', ['must', 'can'], 'can', 'can は許可「〜してよい」を表します。'),
  translateChoice('reg27-28', 'Lesson 27', '助動詞', 'starter', 'He could beat my sister at the party.', '彼はパーティーで私の姉（妹）を負かすことができた。', 'could は過去の能力や可能を表します。', ['彼はパーティーで私の姉（妹）を負かすことができた。', '彼はパーティーで私の姉（妹）に負かされた。', '彼はパーティーで私の姉（妹）を負かすべきだった。', '彼はパーティーで私の姉（妹）に会えなかった。']),
  translateChoice('reg27-29', 'Lesson 27', '助動詞', 'standard', 'She may have been very busy last night.', '彼女は昨夜とても忙しかったのかもしれない。', 'may have been は過去の推量です。', ['彼女は昨夜とても忙しかったのかもしれない。', '彼女は昨夜とても忙しくなければならなかった。', '彼女は昨夜とても忙しかったに違いない。', '彼女は昨夜とても忙しいだろう。']),
  translateChoice('reg27-30', 'Lesson 27', '助動詞', 'starter', 'We used to talk with each other about our dreams for the future.', '私たちは以前、将来の夢についてお互いに話したものだ。', 'used to は過去の習慣を表します。', ['私たちは以前、将来の夢についてお互いに話したものだ。', '私たちは今、将来の夢についてお互いに話している。', '私たちは将来の夢についてお互いに話したい。', '私たちは以前、将来の夢についてお互いに話さなかった。']),
  translateChoice('reg27-31', 'Lesson 27', '助動詞', 'standard', 'I suggest that we start the meeting without him.', '私は彼なしで会議を始めることを提案します。', 'suggest that の後ろでは should を省略した原形が使われます。', ['私は彼なしで会議を始めることを提案します。', '私は彼と一緒に会議を始めることを提案します。', '私は彼なしで会議を終えることを提案しました。', '私は彼なしで会議に出席することを提案します。']),
  fill('reg27-32', 'Lesson 27', '助動詞', 'standard', '彼は一生懸命勉強しなければならなかった。', 'He had to study hard.', '過去の義務は had to で表します。'),
  fill('reg27-33', 'Lesson 27', '助動詞', 'standard', '彼女は私のことを心配しているに違いない。', 'She must be worried about me.', '現在の強い推量は must be です。'),
  fill('reg27-34', 'Lesson 27', '助動詞', 'advanced', '君はそこへ行く必要はなかった。', 'You need not have gone there.', 'need not have + 過去分詞は「実際には行ったが、その必要はなかった」です。', '', ['You need not have gone there.', 'You needn\'t have gone there.']),
  fill('reg27-35', 'Lesson 27', '助動詞', 'advanced', '彼らがそう考えるのも当然だ。', 'It is natural that they should think so.', 'It is natural that ... should ... で当然の判断を表します。', '', ['It is natural that they should think so.', 'It is natural for them to think so.']),

  // Lesson 13: 不定詞 (1)
  reorder('reg13-01', 'Lesson 13', '不定詞・名詞的用法', 'starter', '私たちの目的は貧しい人を助けることです。', ['Our', 'purpose', 'is', 'to', 'help', 'the', 'poor.'], 'Our purpose is to help the poor.', 'to help the poor が be動詞の補語になっています。'),
  reorder('reg13-02', 'Lesson 13', '不定詞・名詞的用法', 'starter', '私たちは船で北海道に行くことを計画した。', ['We', 'planned', 'to', 'go', 'to', 'Hokkaido', 'by', 'ship.'], 'We planned to go to Hokkaido by ship.', 'plan to do は「〜することを計画する」です。'),
  reorder('reg13-03', 'Lesson 13', '不定詞・名詞的用法', 'starter', '外国語を習得するのはとても難しい。', ['It', 'is', 'very', 'hard', 'to', 'master', 'a', 'foreign', 'language.'], 'It is very hard to master a foreign language.', 'It を仮主語にして、to不定詞を後ろに置いています。'),
  reorder('reg13-04', 'Lesson 13', '不定詞・名詞的用法', 'standard', 'トムはその木に登ることは容易だとわかった。', ['Tom', 'found', 'it', 'easy', 'to', 'climb', 'the', 'tree.'], 'Tom found it easy to climb the tree.', 'find it easy to do は「〜するのは容易だとわかる」です。'),
  fill('reg13-05', 'Lesson 13', '不定詞・形容詞的用法', 'starter', 'I have a lot of friends (　　　) (　　　) (　　　).', 'to talk with', 'to talk with が friends を後ろから説明します。', '私は話し相手になってくれる友達がたくさんいます。'),
  fill('reg13-06', 'Lesson 13', '不定詞・形容詞的用法', 'starter', 'Bob bought a book (　　　) (　　　) on the bus.', 'to read', 'to read が「読むための本」という意味で book を修飾します。', 'ボブはバスの中で読む本を買いました。'),
  fill('reg13-07', 'Lesson 13', '不定詞・形容詞的用法', 'starter', 'She has the ability (　　　) (　　　) the work.', 'to do', 'ability to do は「〜する能力」です。', '彼女にはその仕事をする能力があります。'),
  fill('reg13-08', 'Lesson 13', '不定詞・形容詞的用法', 'starter', "He's looking for a house (　　　) (　　　) (　　　).", 'to live in', 'live in の in を残して「住むための家」とします。', '彼は住む家を探しています。', ['to live in', 'to live in it']),
  translateChoice('reg13-09', 'Lesson 13', '不定詞・形容詞的用法', 'starter', 'He is not a person to tell a lie.', '彼はうそをつくような人ではありません。', 'to tell a lie が person を修飾しています。', ['彼はうそをつくような人ではありません。', '彼はうそをつく人を知りません。', '彼はうそをつくように言われた人ではありません。', '彼はうそをつかない人だと話しました。']),
  translateChoice('reg13-10', 'Lesson 13', '不定詞・名詞的用法', 'standard', 'To study a language is to know a different culture.', '言語を学ぶことは、異なる文化を知ることです。', '文頭の to study が主語、to know が補語です。', ['言語を学ぶことは、異なる文化を知ることです。', '言語を学ぶことは、異なる文化を教えることです。', '異なる文化を知ることは、言語を学ぶことです。', '言語を学んだので、異なる文化を知りました。']),
  translateChoice('reg13-11', 'Lesson 13', '不定詞・名詞的用法', 'starter', 'He decided to join the soccer team.', '彼はサッカーチームに入ることを決めました。', 'decide to do は「〜することを決める」です。', ['彼はサッカーチームに入ることを決めました。', '彼はサッカーチームに入ることを忘れました。', '彼はサッカーチームに入るように決められました。', '彼はサッカーチームに入っていると決めました。']),
  translateChoice('reg13-12', 'Lesson 13', '不定詞・形容詞的用法', 'starter', 'I have a lot of homework to hand in next Monday.', '私は来週の月曜日に提出する宿題がたくさんあります。', 'to hand in が homework を修飾します。', ['私は来週の月曜日に提出する宿題がたくさんあります。', '私は来週の月曜日に提出した宿題がたくさんありました。', '私は来週の月曜日に宿題を提出することを決めました。', '私は来週の月曜日に提出する宿題が一つあります。']),
  translateChoice('reg13-13', 'Lesson 13', '不定詞・形容詞的用法', 'starter', "I'm hungry. I want something to eat.", 'お腹が空きました。何か食べるものが欲しいです。', 'something to eat は「食べるもの」です。', ['お腹が空きました。何か食べるものが欲しいです。', 'お腹が空きました。何かを食べている人が欲しいです。', 'お腹がいっぱいです。何か食べるものが欲しいです。', 'お腹が空きました。何も食べたくありません。']),
  fill('reg13-14', 'Lesson 13', '不定詞・名詞的用法', 'standard', '英語を話すことはとても難しい。', 'It is difficult to speak English.', '仮主語 It を使って「〜することは難しい」と表します。', '', ['It is difficult to speak English.', 'To speak English is very difficult.']),

  // Lesson 14: 不定詞 (2)
  translateChoice('reg14-01', 'Lesson 14', '不定詞・副詞的用法', 'standard', 'I went to Harajuku to buy some clothes yesterday.', '私は昨日、服を買うために原宿へ行きました。', 'to buy は目的「〜するために」を表します。', ['私は昨日、服を買うために原宿へ行きました。', '私は昨日、服を買ったあとで原宿へ行きました。', '私は昨日、服を買うために原宿から帰りました。', '私は昨日、服を買わずに原宿へ行きました。']),
  translateChoice('reg14-02', 'Lesson 14', '不定詞・副詞的用法', 'standard', 'He grew up to be a lawyer.', '彼は成長して弁護士になりました。', 'grow up to be は結果「成長して〜になる」です。', ['彼は成長して弁護士になりました。', '彼は弁護士になるために成長しました。', '彼は弁護士を成長させました。', '彼は成長した弁護士に会いました。']),
  translateChoice('reg14-03', 'Lesson 14', '不定詞・副詞的用法', 'standard', 'She is very kind to help them.', '彼女は親切にも彼らを助けてあげました。', '形容詞 + to不定詞で判断の理由を表します。', ['彼女は親切にも彼らを助けてあげました。', '彼女は彼らを助けるのを親切に思いました。', '彼女は彼らを助けてもらって親切でした。', '彼女は彼らを助けるほど冷たかった。']),
  translateChoice('reg14-04', 'Lesson 14', '不定詞・副詞的用法', 'standard', 'I was sad to hear the news.', '私はその知らせを聞いて悲しかった。', '感情の原因を to hear が表します。', ['私はその知らせを聞いて悲しかった。', '私はその知らせを聞くと嬉しかった。', '私はその知らせを聞いて驚きました。', '私はその知らせを聞かないで悲しかった。']),
  translateChoice('reg14-05', 'Lesson 14', '不定詞・副詞的用法', 'standard', 'He was very happy to get the job.', '彼はその仕事を得てとても幸せでした。', 'happy の原因を to get が表します。', ['彼はその仕事を得てとても幸せでした。', '彼はその仕事を得るためにとても幸せでした。', '彼はその仕事を失ってとても幸せでした。', '彼はその仕事を得た人をとても幸せにしました。']),
  fill('reg14-06', 'Lesson 14', 'SVO + 不定詞', 'standard', 'I (　　　) (　　　) (　　　) (　　　) the role.', 'want him to take', 'want + 人 + to do は「人に〜してほしい」です。', '私は彼にその役を演じてほしい。', ['want him to take', 'want him to play']),
  fill('reg14-07', 'Lesson 14', 'SVO + 不定詞', 'standard', 'The police officer (　　　) (　　　) (　　　) (　　　) home.', 'told us to go', 'tell + 人 + to do は「人に〜するように言う」です。', 'その警官は私たちに家に帰るように言いました。'),
  fill('reg14-08', 'Lesson 14', 'SVO + 不定詞', 'standard', 'My parents (　　　) (　　　) (　　　) (　　　) a telescope.', 'allowed me to use', 'allow + 人 + to do は「人が〜するのを許す」です。', '両親は私が望遠鏡を使うのを許してくれました。'),
  fill('reg14-09', 'Lesson 14', 'SVO + 不定詞', 'standard', 'The doctor (　　　) (　　　) (　　　) (　　　) more exercise.', 'advised me to do', 'advise + 人 + to do は「人に〜するよう助言する」です。', '医師は私にもっと運動するように助言しました。'),
  reorder('reg14-10', 'Lesson 14', '意味上の主語', 'standard', 'アンがその机を動かすことは困難だった。', ['It', 'was', 'hard', 'for', 'Anne', 'to', 'move', 'the', 'desk.'], 'It was hard for Anne to move the desk.', 'for + 人 + to do で不定詞の意味上の主語を表します。'),
  reorder('reg14-11', 'Lesson 14', '意味上の主語', 'standard', '他人の気持ちを理解するのは簡単ではない。', ['It', 'is', 'not', 'easy', 'to', 'understand', 'others\'','feelings.'], "It is not easy to understand others' feelings.", 'It is + 形容詞 + to do の形です。'),
  reorder('reg14-12', 'Lesson 14', '意味上の主語', 'standard', 'ドアにかぎをかけないままにしておいたとは、私は不注意だった。', ['I', 'was', 'careless', 'to', 'leave', 'the', 'door', 'unlocked.'], 'I was careless to leave the door unlocked.', '形容詞 + to do で判断の理由を表します。'),
  reorder('reg14-13', 'Lesson 14', '不定詞の否定', 'standard', '私たちはその試合に出場しないことに決めた。', ['We', 'decided', 'not', 'to', 'take', 'part', 'in', 'the', 'game.'], 'We decided not to take part in the game.', '不定詞の否定は not to do です。'),
  fill('reg14-14', 'Lesson 14', 'SVO + 不定詞', 'standard', '私は彼女に宿題を手伝ってくれるように頼んだ。', 'I asked her to help me with my homework.', 'ask + 人 + to do は「人に〜するよう頼む」です。', '', ['I asked her to help me with my homework.', 'I asked her to help with my homework.']),

  // Lesson 15: 不定詞 (3)
  choice('reg15-01', 'Lesson 15', '使役動詞', 'standard', "Maya is out now. I'll [have / let] her call you back when she gets back.", ['have', 'let'], 'have', 'have + O + 動詞の原形で「Oに〜してもらう」です。'),
  choice('reg15-02', 'Lesson 15', '使役動詞', 'standard', "I wanted to go fishing with you, but my father didn't make [let] me go out.", ['let', 'to let'], 'let', 'let + O + 動詞の原形で「Oに〜させる」です。'),
  choice('reg15-03', 'Lesson 15', '使役動詞', 'standard', 'He was [made to go / had to go] to the library with his friends.', ['made to go', 'had to go'], 'made to go', '受動態の make は be made to do になります。'),
  choice('reg15-04', 'Lesson 15', '知覚動詞', 'standard', 'I heard my sister [say / to say] something in her sleep.', ['say', 'to say'], 'say', '知覚動詞 + O + 動詞の原形で、動作全体を聞いたことを表します。'),
  choice('reg15-05', 'Lesson 15', '知覚動詞', 'standard', "I didn't notice Brad [leave / to leave] the house.", ['leave', 'to leave'], 'leave', 'notice + O + 動詞の原形の形です。'),
  choice('reg15-06', 'Lesson 15', '知覚動詞', 'standard', 'The man was seen [enter / to enter] the building.', ['enter', 'to enter'], 'to enter', '知覚動詞の受動態では to不定詞を使います。'),
  fill('reg15-07', 'Lesson 15', 'seem + 不定詞', 'standard', 'It appeared that the gentleman was very rich. The gentleman appeared (　　　) (　　　) very rich.', 'to be', 'appear to be は「〜のようだ」を表します。', 'その紳士はとても裕福だと思われました。'),
  fill('reg15-08', 'Lesson 15', 'seem + 不定詞', 'standard', 'It seemed Mr. Inoue was looking for something. Mr. Inoue seemed (　　　) (　　　) (　　　) for something.', 'to be looking', '進行中の内容は seem to be doing で表します。', '井上氏は何かを探しているようでした。'),
  fill('reg15-09', 'Lesson 15', '完了形の不定詞', 'advanced', 'It seemed that I had left my glasses somewhere. I seemed (　　　) (　　　) (　　　) my glasses somewhere.', 'to have left', 'seem の時点より前のことなので to have + 過去分詞です。', '私はどこかに眼鏡を置き忘れたようでした。'),
  fill('reg15-10', 'Lesson 15', '完了形の不定詞', 'advanced', 'It seems that he was caught in a shower. He seems (　　　) (　　　) (　　　) (　　　) in a shower.', 'to have been caught', '受動態の完了形は to have been + 過去分詞です。', '彼はにわか雨にあったようです。'),
  reorder('reg15-11', 'Lesson 15', '完了形の不定詞', 'advanced', '昨夜、私は誰かが大声で叫ぶのを聞いた。', ['I', 'heard', 'someone', 'cry', 'out', 'last', 'night.'], 'I heard someone cry out last night.', 'hear + O + 動詞の原形の形です。'),
  reorder('reg15-12', 'Lesson 15', 'seem + 不定詞', 'standard', '弟にその場所まで案内させますね。', ['I\'ll', 'have', 'my', 'brother', 'show', 'you', 'the', 'place.'], "I'll have my brother show you the place.", 'have + O + 動詞の原形で依頼・使役を表します。'),
  reorder('reg15-13', 'Lesson 15', '完了形の不定詞', 'advanced', '私は彼らのリーダーに選ばれて運がよかった。', ['I', 'was', 'lucky', 'to', 'have', 'been', 'chosen', 'as', 'their', 'leader.'], 'I was lucky to have been chosen as their leader.', '過去の受動的な出来事を完了形の不定詞で表します。'),
  reorder('reg15-14', 'Lesson 15', '不定詞の受動態', 'advanced', '私はそのパーティーに招待されなくて悲しかった。', ['I', 'was', 'sad', 'not', 'to', 'have', 'been', 'invited', 'to', 'the', 'party.'], 'I was sad not to have been invited to the party.', 'not to have been invited は「招待されなかったこと」を表します。'),
  reorder('reg15-15', 'Lesson 15', '進行形の不定詞', 'standard', 'シンジは今、公園でサッカーをしているようだ。', ['Shinji', 'seems', 'to', 'be', 'playing', 'soccer', 'in', 'the', 'park', 'now.'], 'Shinji seems to be playing soccer in the park now.', '現在進行中のことは seem to be doing です。'),
  fill('reg15-16', 'Lesson 15', '知覚動詞', 'standard', 'なぜ昨日パーティーに来なかったの？ お父さんが私に宿題をさせたんだ。', 'My father made me do my homework.', 'make + O + 動詞の原形で「Oに〜させる」です。', '', ['My father made me do my homework.', 'My father made me study.']),

  // Plus: 不定詞
  translateChoice('regplus-01', 'Plus', '不定詞・独立不定詞', 'advanced', 'We happened to know each other.', '私たちはたまたま知り合った。', 'happen to do は「たまたま〜する」です。', ['私たちはたまたま知り合った。', '私たちはお互いを知ろうと努力した。', '私たちは以前からお互いを知っていた。', '私たちはたまたまお互いを避けた。']),
  translateChoice('regplus-02', 'Plus', '不定詞・be to', 'advanced', 'Satoshi came to understand Italian culture while he was in Rome.', 'サトシはローマにいる間に、イタリア文化を理解するようになった。', 'come to do は「〜するようになる」です。', ['サトシはローマにいる間に、イタリア文化を理解するようになった。', 'サトシはローマにいる間、イタリア文化を教えるようになった。', 'サトシはローマに行く前にイタリア文化を理解していた。', 'サトシはローマでイタリア文化を理解できなかった。']),
  reorder('regplus-03', 'Plus', '不定詞・be to', 'advanced', 'フランス大統領は来月、日本を訪問する予定です。', ['The', 'French', 'President', 'is', 'to', 'visit', 'Japan', 'next', 'month.'], 'The French President is to visit Japan next month.', 'be to do は公的な予定を表します。'),
  reorder('regplus-04', 'Plus', '不定詞・be to', 'advanced', '空には雲一つ見えなかった。', ['Not', 'a', 'cloud', 'was', 'to', 'be', 'seen', 'in', 'the', 'sky.'], 'Not a cloud was to be seen in the sky.', 'be to be seen は「見える・見られる」を表す受動表現です。'),
  reorder('regplus-05', 'Plus', '不定詞・be to', 'advanced', '外出する前に宿題をしなさい。', ['You', 'are', 'to', 'do', 'your', 'homework', 'before', 'you', 'go', 'out.'], 'You are to do your homework before you go out.', 'be to do は命令・義務も表します。'),
  fill('regplus-06', 'Plus', '形容詞 + to不定詞', 'standard', 'It is easy to find the shop. The shop is (　　　) (　　　) (　　　).', 'easy to find', '形容詞 + to do の形で、主語の性質を説明します。', 'その店は見つけやすいです。'),
  fill('regplus-07', 'Plus', '疑問詞 + to不定詞', 'standard', "She didn't know where she should go. She didn't know (　　　) (　　　) go.", 'where to', '疑問詞 + to do は「どこへ〜すべきか」です。', '彼女はどこへ行けばよいのかわかりませんでした。'),
  fill('regplus-08', 'Plus', 'too ... to', 'advanced', "The coat was so expensive that Kevin couldn't buy it. The coat was (　　　) (　　　) for Kevin (　　　) buy.", 'too expensive to', 'too ... for 人 to do は「人が〜できないほど…すぎる」です。', 'そのコートはケビンには高すぎて買えませんでした。'),
  fill('regplus-09', 'Plus', 'so ... as to', 'advanced', 'The man was so kind as (　　　) (　　　) me the way.', 'to show', 'so kind as to do は「親切にも〜する」です。', 'その男性は親切にも私に駅への道を教えてくれました。'),
  fill('regplus-10', 'Plus', 'enough to', 'advanced', 'He is tall (　　　) (　　　) reach the ceiling.', 'enough to', '形容詞 + enough to do は「〜するのに十分…」です。', '彼は天井に手が届くほど背が高い。'),
  fill('regplus-11', 'Plus', '独立不定詞', 'advanced', '(　　　) (　　　) (　　　), I\'m not very good at math.', 'To be honest', 'To be honest は「正直に言って」という独立不定詞です。', '正直に言って、私は数学があまり得意ではありません。'),
  fill('regplus-12', 'Plus', '独立不定詞', 'advanced', 'I don\'t (　　　) (　　　) be an adult.', 'want to', 'want to do は「〜したい」です。', '私は大人になりたくありません。'),
  fill('regplus-13', 'Plus', 'so as to', 'advanced', 'Keiko is saving money so (　　　) (　　　) travel all over the world.', 'as to', 'so as to do は「〜するために」を表します。', 'ケイコは世界中を旅行するためにお金を貯めています。'),
  fill('regplus-14', 'Plus', 'in order to', 'standard', 'I went to the station by taxi in order (　　　) (　　　) miss the train.', 'not to', 'in order not to do は「〜しないために」です。', '電車に乗り遅れないように、私はタクシーで駅まで行きました。'),
  fill('regplus-15', 'Plus', '疑問詞 + to不定詞', 'advanced', 'Would you (　　　) teaching me how to play the guitar?', 'mind', 'Would you mind -ing? は丁寧な依頼です。', 'ギターの弾き方を教えていただけますか。'),
  fill('regplus-16', 'Plus', '独立不定詞', 'advanced', 'To (　　　) (　　　), you should know yourself.', 'begin with', 'To begin with は「まず第一に」という独立不定詞です。', 'まず第一に、あなたは自分自身を知るべきです。'),

  // Lesson 16: 動名詞 (1)
  fill('reg16-01', 'Lesson 16', '動名詞の働き', 'starter', 'Her job is (　　　) English to children.', 'teaching', '動名詞が be動詞の補語になっています。', '彼女の仕事は子どもたちに英語を教えることです。'),
  fill('reg16-02', 'Lesson 16', '動名詞の働き', 'starter', '(　　　) in the park refreshes me.', 'Walking', '動名詞が文の主語になっています。', 'その公園を歩くことは私の気分をさわやかにします。', ['Walking', 'Going for a walk']),
  fill('reg16-03', 'Lesson 16', '動名詞の働き', 'starter', 'I finished (　　　) a letter to Bob last night.', 'writing', 'finish の後ろには動名詞を置きます。', '私は昨夜、ボブへの手紙を書き終えました。'),
  fill('reg16-04', 'Lesson 16', '動名詞の働き', 'starter', "I'm thinking of (　　　) a new pair of glasses this weekend.", 'buying', '前置詞 of の後ろには動名詞を置きます。', '私は今週末、新しい眼鏡を買おうと考えています。'),
  fill('reg16-05', 'Lesson 16', '動名詞の働き', 'starter', "My room needs (　　　), but I don't feel like doing it.", 'cleaning', 'need -ing は「〜される必要がある」です。', '私の部屋は掃除が必要ですが、する気になれません。', ['cleaning', 'to be cleaned']),
  reorder('reg16-06', 'Lesson 16', '動名詞の意味上の主語', 'standard', '彼女は一人で美術館に行くのが好きだ。', ['She', 'likes', 'visiting', 'museums', 'alone.'], 'She likes visiting museums alone.', '動名詞 visiting が likes の目的語です。'),
  reorder('reg16-07', 'Lesson 16', '動名詞の意味上の主語', 'standard', '彼は、娘が歌手であるのを誇りに思っている。', ['He', 'is', 'proud', 'of', 'his', 'daughter', 'being', 'a', 'singer.'], 'He is proud of his daughter being a singer.', '動名詞の意味上の主語は所有格または目的格で表します。'),
  reorder('reg16-08', 'Lesson 16', '動名詞の意味上の主語', 'standard', '野菜を食べないことは健康に悪い。', ['Not', 'eating', 'vegetables', 'is', 'bad', 'for', 'your', 'health.'], 'Not eating vegetables is bad for your health.', '動名詞の否定は not -ing です。'),
  reorder('reg16-09', 'Lesson 16', '動名詞の意味上の主語', 'standard', '私は彼がスーツを着ているのを想像できない。', ['I', 'can\'t', 'imagine', 'him', 'wearing', 'a', 'suit.'], "I can't imagine him wearing a suit.", 'imagine の後ろに動名詞を置きます。'),
  fill('reg16-10', 'Lesson 16', '動名詞・完了形', 'advanced', "He's ashamed of (　　　) (　　　) when he was young. [make mistakes]", 'making mistakes', '過去の行為でも、文脈上明らかなときは動名詞で表します。', '彼は若いころ、よく間違いをしたことを恥じています。', ['making mistakes', 'having made mistakes']),
  fill('reg16-11', 'Lesson 16', '動名詞・受動態', 'advanced', "I don't like (　　　) (　　　) with him. [compare]", 'being compared', '受動態の動名詞は being + 過去分詞です。', '私は彼と比べられるのが好きではありません。', ['being compared', 'being compared with']),
  fill('reg16-12', 'Lesson 16', '動名詞・完了形', 'advanced', 'I regret (　　　) this shirt. [buy]', 'buying', 'regret -ing は「〜したことを後悔する」です。', '私はこのシャツを買ったことを後悔しています。', ['buying', 'having bought']),
  fill('reg16-13', 'Lesson 16', '動名詞', 'standard', '私は友達とサッカーをして楽しんだ。', 'I enjoyed playing soccer with my friends.', 'enjoy の後ろには動名詞を置きます。', '', ['I enjoyed playing soccer with my friends.', 'I had fun playing soccer with my friends.']),

  // Lesson 17: 動名詞 (2)
  fill('reg17-01', 'Lesson 17', '動名詞を使った重要表現', 'standard', 'Wayne is looking (　　　) (　　　) (　　　) to Kochi this summer.', 'forward to going', 'look forward to -ing は「〜を楽しみに待つ」です。', 'ウェインはこの夏、高知に行くことを楽しみにしています。'),
  fill('reg17-02', 'Lesson 17', '動名詞を使った重要表現', 'standard', 'The heavy rain prevented (　　　) (　　　) (　　　) the mountain.', 'me from climbing', 'prevent + O + from -ing は「Oが〜するのを妨げる」です。', '大雨で私はその山に登れませんでした。'),
  fill('reg17-03', 'Lesson 17', '動名詞を使った重要表現', 'standard', "I'm tired. I don't (　　　) (　　　) (　　　) a book this evening.", 'feel like reading', 'feel like -ing は「〜したい気がする」です。', '私は疲れていて、今夜は本を読む気分ではありません。'),
  fill('reg17-04', 'Lesson 17', '動名詞を使った重要表現', 'standard', 'Would you (　　　) (　　　) the window?', 'mind opening', 'Would you mind -ing? は依頼を表します。', '窓を開けていただけますか。'),
  reorder('reg17-05', 'Lesson 17', '動名詞を使った重要表現', 'standard', '彼は手話を使うことに慣れている。', ['He', 'is', 'used', 'to', 'using', 'sign', 'language.'], 'He is used to using sign language.', 'be used to -ing は「〜することに慣れている」です。'),
  reorder('reg17-06', 'Lesson 17', '動名詞を使った重要表現', 'advanced', 'それが本当なのかどうかはわからない。', ['There', 'is', 'no', 'knowing', 'whether', 'it', 'is', 'true', 'or', 'not.'], 'There is no knowing whether it is true or not.', 'There is no -ing は「〜することはできない」です。'),
  reorder('reg17-07', 'Lesson 17', '動名詞を使った重要表現', 'advanced', 'これ以上彼と言い争いをしてもむだだ。', ['It', 'is', 'no', 'use', 'arguing', 'with', 'him', 'any', 'longer.'], 'It is no use arguing with him any longer.', 'It is no use -ing は「〜してもむだだ」です。'),
  choice('reg17-08', 'Lesson 17', '動名詞と不定詞', 'standard', 'Jonathan decided [not to eat / not eating] late at night.', ['not to eat', 'not eating'], 'not to eat', 'decide の後ろは to不定詞です。'),
  choice('reg17-09', 'Lesson 17', '動名詞と不定詞', 'standard', 'Emma enjoyed [to play / playing] the violin yesterday.', ['to play', 'playing'], 'playing', 'enjoy の後ろは動名詞です。'),
  choice('reg17-10', 'Lesson 17', '動名詞と不定詞', 'standard', 'My father gave up [to smoke / smoking] ten years ago.', ['to smoke', 'smoking'], 'smoking', 'give up の後ろは動名詞です。'),
  choice('reg17-11', 'Lesson 17', '動名詞と不定詞', 'standard', 'I hope [to be / being] a professional baseball player in the future.', ['to be', 'being'], 'to be', 'hope の後ろは to不定詞です。'),
  fill('reg17-12', 'Lesson 17', '動名詞と不定詞', 'standard', 'Do you remember (　　　) to this place often when you were small? [come]', 'coming', 'remember -ing は「〜したことを覚えている」です。', 'あなたは小さいときにこの場所によく来たのを覚えていますか。'),
  fill('reg17-13', 'Lesson 17', '動名詞と不定詞', 'standard', 'Please remember (　　　) (　　　) me when you arrive at the airport. [call]', 'to call', 'remember to do は「忘れずに〜する」です。', '空港に着いたら、忘れずに私に電話をかけてください。'),
  fill('reg17-14', 'Lesson 17', '動名詞と不定詞', 'standard', 'She forgot (　　　) her dictionary to school. [bring]', 'bringing', 'forget -ing は「〜したことを忘れる」です。', '彼女は学校に辞書を持ってくるのを忘れました。'),
  fill('reg17-15', 'Lesson 17', '動名詞と不定詞', 'standard', "I'll never forget (　　　) hands with the president. [shake]", 'shaking', 'forget -ing は過去の経験を表します。', '私は大統領と握手したことを決して忘れないでしょう。'),
  fill('reg17-16', 'Lesson 17', '動名詞と不定詞', 'starter', '私は最近テニスを習い始めた。', 'I started playing tennis recently.', 'start は動名詞も不定詞も取れます。', '', ['I started playing tennis recently.', 'I started learning tennis recently.']),

  // Option 4: 名詞構文・無生物主語
  fill('regopt4-01', 'Option 4', '名詞構文', 'standard', 'Ryota runs fast. Ryota is a (　　　) (　　　).', 'fast runner', '副詞を形容詞、動詞を名詞に変えて名詞構文にします。', 'リョウタは速く走ります。リョウタは走るのが速い人です。'),
  fill('regopt4-02', 'Option 4', '名詞構文', 'standard', 'I am grateful that you accepted my invitation. I am grateful for (　　　) (　　　) of my invitation.', 'your acceptance', 'that節を所有格 + 名詞に変えます。', '私は、あなたが招待を受けてくれたことに感謝しています。', ['your acceptance', 'your accepting']),
  fill('regopt4-03', 'Option 4', '名詞構文', 'standard', 'We had no idea that he was safe. We had no idea of (　　　) (　　　).', 'his safety', '形容詞 safe を名詞 safety にします。', '彼が無事だとは思いもしませんでした。'),
  fill('regopt4-04', 'Option 4', '名詞構文', 'standard', 'Sally decided to go to the party. Sally (　　　) (　　　) (　　　) to go to the party.', 'made a decision', 'decide を make a decision に言い換えます。', 'サリーはパーティーに行くことを決めました。'),
  fill('regopt4-05', 'Option 4', '名詞構文', 'standard', 'He was angry because the train arrived late. He was angry about the (　　　) (　　　) of the train.', 'late arrival', 'arrive を arrival に変えます。', '彼は電車が遅れて到着したことに腹を立てていました。'),
  reorder('regopt4-06', 'Option 4', '無生物主語', 'standard', 'その話を聞いて、彼女は自分の考え方を変えた。', ['The', 'story', 'made', 'her', 'change', 'her', 'way', 'of', 'thinking.'], 'The story made her change her way of thinking.', '無生物主語 + make + O + 動詞の原形の形です。'),
  reorder('regopt4-07', 'Option 4', '無生物主語', 'standard', '祖父は医師の助言のおかげで、病気から回復することができた。', ['The', 'doctor\'s', 'advice', 'enabled', 'my', 'grandfather', 'to', 'recover', 'from', 'his', 'illness.'], "The doctor's advice enabled my grandfather to recover from his illness.", 'enable + O + to do は「Oが〜できるようにする」です。'),
  reorder('regopt4-08', 'Option 4', '無生物主語', 'standard', '私はプライドのせいで、友だちに助けを求めることができなかった。', ['My', 'pride', 'kept', 'me', 'from', 'asking', 'my', 'friends', 'for', 'help.'], 'My pride kept me from asking my friends for help.', 'keep + O + from -ing は「Oが〜するのを妨げる」です。'),
  reorder('regopt4-09', 'Option 4', '無生物主語', 'standard', '事故のせいで、私たちは時間どおりに駅に到着できなかった。', ['The', 'accident', 'prevented', 'us', 'from', 'arriving', 'at', 'the', 'station', 'on', 'time.'], 'The accident prevented us from arriving at the station on time.', 'prevent + O + from -ing の形です。'),
  reorder('regopt4-10', 'Option 4', '無生物主語', 'standard', '彼の手紙には、彼が4月に私たちを訪れると書いてあった。', ['His', 'letter', 'said', 'that', 'he', 'would', 'visit', 'us', 'in', 'April.'], 'His letter said that he would visit us in April.', '無生物主語の say は「〜と書いてある」です。'),
  translateChoice('regopt4-11', 'Option 4', '名詞構文', 'starter', 'Let me have a look at that.', 'それをちょっと見せてください。', 'have a look は take a look と同じ「見る」です。', ['それをちょっと見せてください。', 'それを少し聞かせてください。', 'それをちょっと貸してください。', 'それをもう一度説明してください。']),
  translateChoice('regopt4-12', 'Option 4', '名詞構文', 'starter', 'My sister is an early riser.', '私の姉（妹）は早起きです。', 'early riser は「早起きする人」です。', ['私の姉（妹）は早起きです。', '私の姉（妹）は夜更かしです。', '私の姉（妹）は早く走ります。', '私の姉（妹）は朝食を作ります。']),
  translateChoice('regopt4-13', 'Option 4', '無生物主語', 'standard', 'The Internet allows us to get a lot of information.', 'インターネットのおかげで、私たちは多くの情報を得ることができます。', 'allow + O + to do は「Oが〜するのを可能にする」です。', ['インターネットのおかげで、私たちは多くの情報を得ることができます。', 'インターネットのおかげで、私たちは多くの情報を失います。', 'インターネットは私たちに多くの情報を教えることを許しません。', '私たちはインターネットを使わずに多くの情報を得られます。']),
  translateChoice('regopt4-14', 'Option 4', '無生物主語', 'standard', 'The typhoon stopped us from going fishing in the sea.', '台風のため、私たちは海へ釣りに行けませんでした。', 'stop + O + from -ing は「Oが〜するのを妨げる」です。', ['台風のため、私たちは海へ釣りに行けませんでした。', '台風のおかげで、私たちは海へ釣りに行きました。', '台風のため、私たちは海で釣りを楽しみました。', '台風は私たちに海へ釣りに行くよう促しました。']),
  translateChoice('regopt4-15', 'Option 4', '無生物主語', 'starter', 'Will this bus take us to the airport?', 'このバスで空港へ行けますか。', '無生物主語の take は「連れていく」を表します。', ['このバスで空港へ行けますか。', 'このバスは空港から来ますか。', 'このバスで空港へ行く人を見ましたか。', 'このバスは空港へ行かずに停まりますか。']),

  // Option 7: 前置詞
  fill('regopt7-01', 'Option 7', 'at / in / on', 'starter', 'Please pick me up (　　　) the station.', 'at', 'at は場所の一点を表します。', '駅で私を拾ってください。'),
  fill('regopt7-02', 'Option 7', 'at / in / on', 'starter', 'This library closes (　　　) 9 o\'clock.', 'at', '時刻の一点には at を使います。', 'この図書館は9時に閉まります。'),
  fill('regopt7-03', 'Option 7', 'at / in / on', 'starter', 'My sister was born (　　　) July 20th.', 'on', '特定の日には on を使います。', '私の姉（妹）は7月20日に生まれました。'),
  fill('regopt7-04', 'Option 7', 'at / in / on', 'starter', 'Sarah and Tom are going to get married (　　　) June.', 'in', '月・年など長さのある期間には in を使います。', 'サラとトムは6月に結婚する予定です。'),
  fill('regopt7-05', 'Option 7', 'at / in / on', 'starter', 'I put up a new clock (　　　) the wall (　　　) my room.', 'on ... in', '壁との接触面には on、部屋の内部には in を使います。', '私は部屋の壁に新しい時計を掛けました。', ['on ... in', 'on the wall in']),
  choice('regopt7-06', 'Option 7', 'from / to / for', 'starter', 'The restaurant is open [from / to] 11 a.m. [from / to] 11 p.m.', ['from ... to', 'to ... from'], 'from ... to', 'from A to B は「AからBまで」です。'),
  choice('regopt7-07', 'Option 7', 'from / to / for', 'starter', 'I visited my grandparents [during / for] the winter vacation.', ['during', 'for'], 'during', 'during + 特定の期間で「〜の間に」です。'),
  choice('regopt7-08', 'Option 7', 'from / to / for', 'starter', 'I stayed in Hong Kong [in / for] a week.', ['in', 'for'], 'for', 'for + 期間で「〜の間」です。'),
  choice('regopt7-09', 'Option 7', 'from / to / for', 'starter', 'The train [for / to] Atami will depart [in / for] five minutes.', ['for ... in', 'to ... for'], 'for ... in', 'for は目的地、in は「〜後」を表します。'),
  reorder('regopt7-10', 'Option 7', '前置詞の使い分け', 'standard', '彼女の最新アルバムの題名を知っていますか。', ['Do', 'you', 'know', 'the', 'title', 'of', 'her', 'latest', 'album?'], 'Do you know the title of her latest album?', 'of は所属・所有を表します。'),
  reorder('regopt7-11', 'Option 7', '前置詞の使い分け', 'standard', '私たちは校庭から雪を取り除いた。', ['We', 'cleared', 'the', 'schoolyard', 'of', 'snow.'], 'We cleared the schoolyard of snow.', 'clear A of B は「AからBを取り除く」です。'),
  reorder('regopt7-12', 'Option 7', '前置詞の使い分け', 'starter', 'その犬は玄関のそばに座っていた。', ['The', 'dog', 'was', 'sitting', 'by', 'the', 'front', 'door.'], 'The dog was sitting by the front door.', 'by は「〜のそばに」を表します。'),
  reorder('regopt7-13', 'Option 7', '前置詞の使い分け', 'standard', '私は昨日、ショッピングモールで先生が家族といるのを見た。', ['I', 'saw', 'my', 'teacher', 'with', 'his', 'family', 'at', 'the', 'mall', 'yesterday.'], 'I saw my teacher with his family at the mall yesterday.', 'with は同伴、at は場所を表します。'),
  choice('regopt7-14', 'Option 7', '前置詞の使い分け', 'starter', 'I will finish my report [by / until] four, so please wait [by / until] then.', ['by ... until', 'until ... by'], 'by ... until', 'by は期限、until は継続の終点です。'),
  choice('regopt7-15', 'Option 7', '前置詞の使い分け', 'starter', 'I drew the picture [by / with] a ball-point pen.', ['by', 'with'], 'with', '道具には with を使います。'),
  choice('regopt7-16', 'Option 7', '前置詞の使い分け', 'starter', 'I usually go to school [by / with] bike.', ['by', 'with'], 'by', '交通手段には by を使います。'),
]
